version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27020:27017
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8085:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
